repos:
-   hooks:
    -   id: check-json
    -   id: check-toml
    -   id: check-yaml
    -   id: check-case-conflict
    -   id: trailing-whitespace
    -   id: check-merge-conflict
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
-   hooks:
    -   id: uv-lock
    repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.21
-   hooks:
    -   id: absolufy-imports
    repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
-   hooks:
    -   args:
        -   --fix
        id: ruff
    -   id: ruff-format
    repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
-   hooks:
    -   id: pyleft
    repo: https://github.com/nathanvaughn/pyleft
    rev: 1.2.2
-   hooks:
    -   id: pyright
    repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.407
-   hooks:
    -   id: markdownlint
    repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
